package com.vcars.enums;

public enum Marks {

	HIACE, CARINA, COROLLA, CORONA, MARKII, CRESTA, PRADO, PAJERO,
	PROBOX, IPSUM, HUMMER, HARRIER, IST, MAHINDRA, MAZDA, TOYOTA, TOYOPET,
	CALDINA, HYUNDAI, POLO, PEUJOT, MITSUBISHI
}
